/* ApiPathsEnum */
export enum ApiPathsEnum {
  APP_UTILS = "/app-utils",
  AUTH = "/auth",
  ENVIRONMENTAL_MATRIX = "/environmental-matrices",
  GENERIC_CLASS_OR_CATEGORY_OF_HAZARD = "/generic-classes-or-categories-of-hazard",
  GENERIC_PARAMETER = "/generic-parameters",
  GENERIC_PARAMETER_OF_SAMPLE = "/generic-parameters-of-samples",
  IMPORT = "/imports",
  LABORATORY = "/laboratories",
  LABORATORY_ANALYSIS = "/laboratories-analyses",
  LGR_CHAPTER = "/lgr-chapters",
  PUBLISHER = "/publishers",
  QUALITY_STANDARD_FOR_GENERIC_PARAMETERS = "/quality-standards-for-generic-parameters",
  REGULATION = "/regulations",
  RAG = "/rag",
  SAMPLE = "/samples",
  SAMPLING_POINT = "/sampling-points",
  SCOCOH_OF_TOXIC_PARAMETER = "/scocohs-of-toxic-parameters",
  TOXIC_PARAMETER = "/toxic-parameters",
  TOXIC_PARAMETER_OF_SAMPLE = "/toxic-parameters-of-samples",
  UNIT = "/units",
}
